---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: my-app
spec:
  encryptedData:
    password: AgA3WJ77tDWgydVrognvCYUSiNkTUgcDa/qpAQCP8grhqYaER3GmHER838J4dUS04SsBMqWFFv87AnEtFTd2pd2pckra4eRic+OaHqxAiPJ+f3TjmYHqfD2g8mYJ8dzgQ9z1Pw3Gz0f7ThEXddFZL5fZd/AbIitBGmou8LQBSEktPDqmu7XQeCtJDu08LTP4xfPBIeEms8ogKoGR7LR34NKtKiS41xb+g/bcDUwUeXD7m3S5nkiOt0v+y0arL6Ki68XrWccfv2KgWRhM5FT/7VTt702hGqp9tbee3UJFJGAVqj1NvXy1NhFJF6+FSK/GqChMLCHBdGDWM18cAoTcEM0jWLD1fQQ7MFUKE3MuCgfeXr9niT4rHfelze8/4rL/Zf/zBmeq+bdt6W1TbHKsKNBZ5d59hym04CqJa0AOxgHyhPOWH8V9YNzBtObxlBOEWuzzqJl8iOZV6lTOaoWBFhIi5sIWBi+URbgxlkYyHRyGQeYgRhvp5NBBGBp8yrVxyWGCXaYFYzcUttXB1tjcfm8HLqDfAad5qmfOM+naKnjHpssjO3zHP8YGcnaf4Zt0gAFy3EJ6oVuLTCwgCstVTrOBDRchbhS98LvzfBKdqwXS9mzcA6PQJs+qDc0RO02L20HtqtXeWPVlT0+3B7+aYao/drLvtCvLSnkgdueWX3Rxkx9Lyv83hgBg+VWS3EOvz1Y69+ez+cOWCQ==
    username: AgCPxa1sIqIHkhynXLVzoAzUHtV2ZochqrXiLHXTR5zTuRowfYNgpySqaJdoZmN8v1Nu6kVElZ6gbhkv30t/iqmcVGjr6PEnRxKRnG/phw3vxwpQl/p3UT02XxmzAyy+WDGyDDuuHllhJ6D4Kuh8xsvRp0bTJvzLkOUmN9v4QnZ2TcYLFPV7eT5H2W7gm0lyEyH09SxLgxntYGD128ttmCKlL9FwuHMTFbSGrsHwirQ/XBD9G06oMvKNNUKl5mjOiOjvw1/eMFsMqEWO2DShlfDkPgAdJ6j8Xke7RqQ+i7h+1X9tyOLK/7bvGwOiPHb4m6QACrcyxoecPJN0QpOfXnaFY93BbqOw3/3tT7GJv9IJQ63X2kkIyYhEObOWsfzi87AGPrx1hHXMbK0tfBXmYespifJj/Ch+k6EzCShafOHZ+D4O/E2JkyMGCd+ONTLqevPml828bFGVGn8uQVUGe0g0/IPauJrPeoaVg75php/zV6Ug6plZ68hK+9vPB0bVxwkEXWn2kKrCd2nnErsV7u0xU99Cu1b6UKH0NilbQULdGC+uyBg6ZhGM8kQc4CdkEOnIUnmL2IUUoR8qY0qHsuLuRjljOYQP/BPZ2oVohOmq9/yyxxyLmZe07B8hdHHzpmPON0yLJERsAQ0b96xThUvLVgJdKHoJ1+z0xY9OzgKT+osmjSiCnG7l5DnA6CJgTYlkxRrtOQ==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: my-app
