pipeline {
    agent any

    environment {
        // ID учетных данных, созданных в Jenkins
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials') 
        GIT_CREDENTIALS = credentials('github-token') 
        
        // Переменные извлекаются из Credentials Manager
        DOCKERHUB_USERNAME = DOCKERHUB_CREDENTIALS_USR
        DOCKERHUB_PASSWORD = DOCKERHUB_CREDENTIALS_PSW
        
        // Используем ваш логин DockerHub и имя образа
        DOCKER_IMAGE_NAME = "Flaxen/fastapi-app" 
        
        // Ваш репозиторий
        GIT_REPO_URL = "https://github.com/Flaxeny/jenkins_flux.git"
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Клонируем ветку main
                git branch: 'master', url: GIT_REPO_URL
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    // Используем короткий хэш коммита как тег для уникальности
                    def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def dockerImageTag = "${DOCKER_IMAGE_NAME}:${commitHash}"
                    
                    // Собираем образ
                    sh "docker build -t ${dockerImageTag} ./app"
                    
                    // Авторизуемся в Docker Hub и пушим образ
                    sh "echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin"
                    sh "docker push ${dockerImageTag}"
                }
            }
        }

        stage('Update & Commit Manifest') {
            steps {
                script {
                    def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def dockerImageTag = "${DOCKER_IMAGE_NAME}:${commitHash}"
                    
                    // Обновляем image в файле deployment.yaml с помощью yq
                    sh "yq e '.spec.template.spec.containers[0].image = \"${dockerImageTag}\"' -i k8s/base/fastapi-app/deployment.yaml"
                    
                    // Настраиваем Git для коммита
                    sh "git config --global user.email 'romskor11@gmail.com'"
                    sh "git config --global user.name 'romskor'"
                    sh "git add k8s/base/fastapi-app/deployment.yaml"
                    
                    // Коммитим изменения
                    sh "git commit -m 'ci: update image to ${dockerImageTag}'"
                    
                    // Пушим изменения в репозиторий, используя токен
                    // Обратите внимание на 'x-access-token' для токена GitHub
                    sh "git push https://x-access-token:${GIT_CREDENTIALS}@github.com/Flaxeny/jenkins_flux.git HEAD:master"
                }
            }
        }
    }
}
