pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = "flaxen/fastapi-app"
        GIT_REPO_URL = "https://github.com/Flaxeny/jenkins_flux.git"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: "${env.GIT_REPO_URL}"
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def dockerImageTag = "${env.DOCKER_IMAGE_NAME}:${commitHash}"

                    sh "docker build -t ${dockerImageTag} ./app"

                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        '''
                        sh "docker push ${dockerImageTag}"
                    }
                }
            }
        }

        stage('Update & Commit Manifest') {
            steps {
                script {
                    def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def dockerImageTag = "${env.DOCKER_IMAGE_NAME}:${commitHash}"

                    // Обновляем манифест
                    sh "yq e '.spec.template.spec.containers[0].image = \"${dockerImageTag}\"' -i k8s/base/fastapi-app/deployment.yaml"

                    // Git конфигурация
                    sh "git config --global user.email 'romskor11@gmail.com'"
                    sh "git config --global user.name 'romskor'"
                    sh "git add k8s/base/fastapi-app/deployment.yaml"
                    sh "git commit -m 'ci: update image to ${dockerImageTag}' || echo 'No changes to commit.'"

                    // Push с токеном GitHub
                    withCredentials([string(credentialsId: 'github-token', variable: 'GIT_TOKEN')]) {
                        sh '''
                            git push https://x-access-token:$GIT_TOKEN@github.com/Flaxeny/jenkins_flux.git HEAD:master
                        '''
                    }
                }
            }
        }
    }
}

