apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
<<<<<<< HEAD
      - name: fastapi-app
        image: flaxen/fastapi-app:commitHash 
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
=======
        - name: fastapi-app
          image: flaxen/fastapi-app:0268b67
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
>>>>>>> 79855e215a155ea5d2f76a93e60b902b4eedaa26
